/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Alvaro' at '19/01/16 9:16' with Gradle 2.6
 *
 * @author Alvaro, @date 19/01/16 9:16
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
