/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Alvaro' at '9/02/16 9:26' with Gradle 2.6
 *
 * @author Alvaro, @date 9/02/16 9:26
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
